{
  "0xcafe::nested": {
    "file": "<TEMPDIR>/nested.move",
    "span": [
      1,
      9
    ],
    "friends": [],
    "attributes": [],
    "functions": [
      {
        "name": "apply",
        "file": "<TEMPDIR>/nested.move",
        "span": [
          4,
          4
        ],
        "visibility": "internal",
        "isEntry": false,
        "isInline": false,
        "isNative": false,
        "isView": false,
        "attributes": [],
        "typeParams": [],
        "params": [
          {
            "name": "f",
            "type": "|u64|u64"
          },
          {
            "name": "x",
            "type": "u64"
          }
        ],
        "returnTypes": [
          "u64"
        ],
        "acquiresDeclared": [],
        "readsDeclared": [],
        "writesDeclared": [],
        "acquiresInferred": [],
        "resourceAccess": {
          "reads": [],
          "writes": []
        },
        "createsClosures": [],
        "invokesFunctionValues": true,
        "effectsComplete": false,
        "isLambdaLifted": false
      },
      {
        "name": "outer",
        "file": "<TEMPDIR>/nested.move",
        "span": [
          6,
          8
        ],
        "visibility": "public",
        "isEntry": false,
        "isInline": false,
        "isNative": false,
        "isView": false,
        "attributes": [],
        "typeParams": [],
        "params": [
          {
            "name": "c",
            "type": "u64"
          }
        ],
        "returnTypes": [
          "u64"
        ],
        "acquiresDeclared": [],
        "readsDeclared": [],
        "writesDeclared": [],
        "acquiresInferred": [
          "0xcafe::nested::R"
        ],
        "resourceAccess": {
          "reads": [],
          "writes": []
        },
        "createsClosures": [
          "0xcafe::nested::__lambda__2__outer"
        ],
        "invokesFunctionValues": false,
        "effectsComplete": true,
        "isLambdaLifted": false
      },
      {
        "name": "__lambda__1__outer",
        "file": "<TEMPDIR>/nested.move",
        "span": [
          7,
          7
        ],
        "visibility": "internal",
        "isEntry": false,
        "isInline": false,
        "isNative": false,
        "isView": false,
        "attributes": [],
        "typeParams": [],
        "params": [
          {
            "name": "c",
            "type": "u64"
          },
          {
            "name": "x",
            "type": "u64"
          },
          {
            "name": "y",
            "type": "u64"
          }
        ],
        "returnTypes": [
          "u64"
        ],
        "acquiresDeclared": [],
        "readsDeclared": [],
        "writesDeclared": [],
        "acquiresInferred": [
          "0xcafe::nested::R"
        ],
        "resourceAccess": {
          "reads": [
            "0xcafe::nested::R"
          ],
          "writes": []
        },
        "createsClosures": [],
        "invokesFunctionValues": false,
        "effectsComplete": true,
        "isLambdaLifted": true,
        "definedIn": "outer"
      },
      {
        "name": "__lambda__2__outer",
        "file": "<TEMPDIR>/nested.move",
        "span": [
          7,
          7
        ],
        "visibility": "internal",
        "isEntry": false,
        "isInline": false,
        "isNative": false,
        "isView": false,
        "attributes": [],
        "typeParams": [],
        "params": [
          {
            "name": "c",
            "type": "u64"
          },
          {
            "name": "x",
            "type": "u64"
          }
        ],
        "returnTypes": [
          "u64"
        ],
        "acquiresDeclared": [],
        "readsDeclared": [],
        "writesDeclared": [],
        "acquiresInferred": [],
        "resourceAccess": {
          "reads": [],
          "writes": []
        },
        "createsClosures": [
          "0xcafe::nested::__lambda__1__outer"
        ],
        "invokesFunctionValues": false,
        "effectsComplete": true,
        "isLambdaLifted": true,
        "definedIn": "outer"
      }
    ],
    "structs": [
      {
        "kind": "struct",
        "name": "R",
        "file": "<TEMPDIR>/nested.move",
        "span": [
          2,
          2
        ],
        "abilities": [
          "key"
        ],
        "typeParams": [],
        "fields": [
          {
            "name": "v",
            "type": "u64",
            "positional": false
          }
        ],
        "attributes": []
      }
    ],
    "constants": []
  }
}
