{
  "0xcafe::invoked": {
    "file": "<TEMPDIR>/invoked.move",
    "span": [
      1,
      16
    ],
    "friends": [],
    "attributes": [],
    "functions": [
      {
        "name": "chain",
        "file": "<TEMPDIR>/invoked.move",
        "span": [
          13,
          15
        ],
        "visibility": "public",
        "isEntry": false,
        "isInline": false,
        "isNative": false,
        "isView": false,
        "attributes": [],
        "typeParams": [],
        "params": [],
        "returnTypes": [
          "u64"
        ],
        "acquiresDeclared": [],
        "readsDeclared": [],
        "writesDeclared": [],
        "acquiresInferred": [
          "0xcafe::invoked::R"
        ],
        "resourceAccess": {
          "reads": [],
          "writes": []
        },
        "createsClosures": [
          "0xcafe::invoked::__lambda__1__chain"
        ],
        "invokesFunctionValues": false,
        "effectsComplete": true,
        "isLambdaLifted": false
      },
      {
        "name": "immediate",
        "file": "<TEMPDIR>/invoked.move",
        "span": [
          8,
          11
        ],
        "visibility": "public",
        "isEntry": false,
        "isInline": false,
        "isNative": false,
        "isView": false,
        "attributes": [],
        "typeParams": [],
        "params": [],
        "returnTypes": [
          "u64"
        ],
        "acquiresDeclared": [],
        "readsDeclared": [],
        "writesDeclared": [],
        "acquiresInferred": [
          "0xcafe::invoked::R"
        ],
        "resourceAccess": {
          "reads": [],
          "writes": []
        },
        "createsClosures": [
          "0xcafe::invoked::__lambda__1__immediate"
        ],
        "invokesFunctionValues": true,
        "effectsComplete": false,
        "isLambdaLifted": false
      },
      {
        "name": "run",
        "file": "<TEMPDIR>/invoked.move",
        "span": [
          4,
          6
        ],
        "visibility": "internal",
        "isEntry": false,
        "isInline": false,
        "isNative": false,
        "isView": false,
        "attributes": [],
        "typeParams": [],
        "params": [
          {
            "name": "f",
            "type": "||u64"
          }
        ],
        "returnTypes": [
          "u64"
        ],
        "acquiresDeclared": [],
        "readsDeclared": [],
        "writesDeclared": [],
        "acquiresInferred": [],
        "resourceAccess": {
          "reads": [],
          "writes": []
        },
        "createsClosures": [],
        "invokesFunctionValues": true,
        "effectsComplete": false,
        "isLambdaLifted": false
      },
      {
        "name": "__lambda__1__chain",
        "file": "<TEMPDIR>/invoked.move",
        "span": [
          14,
          14
        ],
        "visibility": "internal",
        "isEntry": false,
        "isInline": false,
        "isNative": false,
        "isView": false,
        "attributes": [],
        "typeParams": [],
        "params": [],
        "returnTypes": [
          "u64"
        ],
        "acquiresDeclared": [],
        "readsDeclared": [],
        "writesDeclared": [],
        "acquiresInferred": [
          "0xcafe::invoked::R"
        ],
        "resourceAccess": {
          "reads": [
            "0xcafe::invoked::R"
          ],
          "writes": []
        },
        "createsClosures": [],
        "invokesFunctionValues": false,
        "effectsComplete": true,
        "isLambdaLifted": true,
        "definedIn": "chain"
      },
      {
        "name": "__lambda__1__immediate",
        "file": "<TEMPDIR>/invoked.move",
        "span": [
          9,
          9
        ],
        "visibility": "internal",
        "isEntry": false,
        "isInline": false,
        "isNative": false,
        "isView": false,
        "attributes": [],
        "typeParams": [],
        "params": [],
        "returnTypes": [
          "u64"
        ],
        "acquiresDeclared": [],
        "readsDeclared": [],
        "writesDeclared": [],
        "acquiresInferred": [
          "0xcafe::invoked::R"
        ],
        "resourceAccess": {
          "reads": [
            "0xcafe::invoked::R"
          ],
          "writes": []
        },
        "createsClosures": [],
        "invokesFunctionValues": false,
        "effectsComplete": true,
        "isLambdaLifted": true,
        "definedIn": "immediate"
      }
    ],
    "structs": [
      {
        "kind": "struct",
        "name": "R",
        "file": "<TEMPDIR>/invoked.move",
        "span": [
          2,
          2
        ],
        "abilities": [
          "key"
        ],
        "typeParams": [],
        "fields": [
          {
            "name": "v",
            "type": "u64",
            "positional": false
          }
        ],
        "attributes": []
      }
    ],
    "constants": []
  }
}
