{
  "0xcafe::tag": {
    "file": "<TEMPDIR>/tag.move",
    "span": [
      1,
      9
    ],
    "friends": [],
    "attributes": [],
    "functions": [
      {
        "name": "apply",
        "file": "<TEMPDIR>/tag.move",
        "span": [
          2,
          2
        ],
        "visibility": "internal",
        "isEntry": false,
        "isInline": false,
        "isNative": false,
        "isView": false,
        "attributes": [],
        "typeParams": [],
        "params": [
          {
            "name": "f",
            "type": "|u64|u64"
          },
          {
            "name": "x",
            "type": "u64"
          }
        ],
        "returnTypes": [
          "u64"
        ],
        "acquiresInferred": [],
        "resourceAccess": {
          "reads": [],
          "writes": []
        },
        "createsClosures": [],
        "invokesFunctionValues": true,
        "effectsComplete": false,
        "isLambdaLifted": false
      },
      {
        "name": "real_closure",
        "file": "<TEMPDIR>/tag.move",
        "span": [
          6,
          8
        ],
        "visibility": "public",
        "isEntry": false,
        "isInline": false,
        "isNative": false,
        "isView": false,
        "attributes": [],
        "typeParams": [],
        "params": [
          {
            "name": "c",
            "type": "u64"
          }
        ],
        "returnTypes": [
          "u64"
        ],
        "acquiresInferred": [],
        "resourceAccess": {
          "reads": [],
          "writes": []
        },
        "createsClosures": [
          "0xcafe::tag::__lambda__1__real_closure"
        ],
        "invokesFunctionValues": false,
        "effectsComplete": true,
        "isLambdaLifted": false
      },
      {
        "name": "run__lambda__step",
        "file": "<TEMPDIR>/tag.move",
        "span": [
          4,
          4
        ],
        "visibility": "public",
        "isEntry": false,
        "isInline": false,
        "isNative": false,
        "isView": false,
        "attributes": [],
        "typeParams": [],
        "params": [
          {
            "name": "x",
            "type": "u64"
          }
        ],
        "returnTypes": [
          "u64"
        ],
        "acquiresInferred": [],
        "resourceAccess": {
          "reads": [],
          "writes": []
        },
        "createsClosures": [],
        "invokesFunctionValues": false,
        "effectsComplete": true,
        "isLambdaLifted": false
      },
      {
        "name": "__lambda__1__real_closure",
        "file": "<TEMPDIR>/tag.move",
        "span": [
          7,
          7
        ],
        "visibility": "internal",
        "isEntry": false,
        "isInline": false,
        "isNative": false,
        "isView": false,
        "attributes": [],
        "typeParams": [],
        "params": [
          {
            "name": "c",
            "type": "u64"
          },
          {
            "name": "y",
            "type": "u64"
          }
        ],
        "returnTypes": [
          "u64"
        ],
        "acquiresInferred": [],
        "resourceAccess": {
          "reads": [],
          "writes": []
        },
        "createsClosures": [],
        "invokesFunctionValues": false,
        "effectsComplete": true,
        "isLambdaLifted": true,
        "definedIn": "real_closure"
      }
    ],
    "structs": [],
    "constants": []
  }
}
