{
  "0xcafe::token": {
    "constants": [
      {
        "name": "MAX_SUPPLY",
        "type": "u64",
        "value": "1000000"
      }
    ],
    "structs": [
      {
        "name": "Token",
        "abilities": [
          "store",
          "key"
        ],
        "fields": [
          "value: u64",
          "owner: address"
        ]
      }
    ],
    "functions": [
      {
        "name": "burn",
        "signature": "public entry fun burn(t: 0xcafe::token::Token)",
        "isLambdaLifted": false
      },
      {
        "name": "holds",
        "signature": "package fun holds(t: &0xcafe::token::Token): bool",
        "isLambdaLifted": false
      },
      {
        "name": "mint",
        "signature": "public fun mint(amount: u64, owner: address): 0xcafe::token::Token",
        "isLambdaLifted": false
      }
    ]
  }
}
